stages:
  - stage:
    displayName: UploaderStage
    jobs:
      - job:
        displayName: UploaderJob
        steps:
          - pwsh: '1..1000 | % { New-Item "$(Pipeline.Workspace)/$_.txt" -ItemType File -Value $_ } | % { Write-Host "##vso[artifact.upload artifactname=uploadedresult;]$($_.FullName)" }'
  - stage:
    dependsOn: []
    displayName: ConsumerStage
    jobs:
      - job:
        displayName: ConsumerJob
        steps:
          - pwsh: 'Start-Sleep -Seconds 25; 1..100 | % { irm "https://dev.azure.com/TylerLeonhardt/Azure%20Pipelines%20Playground/_apis/build/builds/$(Build.BuildId)/artifacts?api-version=6.1-preview.5" -Headers @{ Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN" } | measure }'
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

