stages:
  - stage:
    dependsOn: []
    displayName: UploaderStageArtifact
    jobs:
      - job:
        displayName: UploaderJobArtifact
        steps:
          - pwsh: |
              1..500 | % {
                $itemCreated = New-Item "$(Pipeline.Workspace)/$_.txt" -ItemType File -Value $_
                Write-Host "artifact.upload; containerfolder=$_; artifactname=$_; $($itemCreated.FullName)"
                Write-Host "##vso[artifact.upload containerfolder=$_;artifactname=$_;]$($itemCreated.FullName)"
                Start-Sleep -Milliseconds 100
              }
          - publish: $(Pipeline.Workspace)/1.txt
            artifact: 1ALT
          - publish: $(Pipeline.Workspace)/2.txt
            artifact: 2ALT
  - stage:
    variables:
      - name: BUILDS_API_URL
        value: $(System.CollectionUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/
    dependsOn: []
    displayName: ConsumerStageArtifact
    jobs:
      - job:
        displayName: ConsumerJobArtifact
        steps:
          - pwsh: |
              do {
                Start-Sleep -Seconds 5

                # Will print out how many we have
                $res = Invoke-RestMethod "$(BUILDS_API_URL)artifacts?api-version=6.0" -Headers @{ Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN" }
                $res
                
                # Get the timeline and see if it says the other stage completed
                $timeline = Invoke-RestMethod "$(BUILDS_API_URL)timeline?api-version=6.0" -Headers @{ Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN" }
                $otherStageFinished = $timeline.records | Where-Object { $_.type -eq 'stage' -and $_.state -eq 'completed' }
                Write-Host "Completed: $(${otherStageFinished}?.type ? 'yes' : 'no')"
                
                # While the other stage is still running
              } while (!$otherStageFinished)
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
