stages:
  - stage:
    displayName: UploaderStage
    jobs:
      - job:
        displayName: UploaderJob
        steps:
          - pwsh: |
              1..1000 | % {
                $itemCreated = New-Item "$(Pipeline.Workspace)/$_.txt" -ItemType File -Value $_
                Write-Host "task.addattachment; type=myattachmenttype; name=$_; $($itemCreated.FullName)"
                Write-Host "##vso[task.addattachment type=myattachmenttype;name=$_;]$($itemCreated.FullName)"
              }
  - stage:
    dependsOn: []
    displayName: ConsumerStage
    jobs:
      - job:
        displayName: ConsumerJob
        steps:
          - pwsh: |
              1..100 | % {
                $res = irm "https://dev.azure.com/TylerLeonhardt/Azure%20Pipelines%20Playground/_apis/build/builds/$(Build.BuildId)/attachments/myattachmenttype?api-version=6.1-preview.2" -Headers @{ Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN" }
                $res
                Start-Sleep -Seconds 1
              }
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

